# Generated by Django 4.2.9 on 2024-02-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='developer',
        ),
    ]
