# Generated by Django 5.0.2 on 2024-02-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
