# Generated by Django 4.2.6 on 2024-02-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_task_categories_user_name_user_phone_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Board Manager', 'Board Manager'), ('Developer', 'Developer')], max_length=20),
        ),
    ]
