# Generated by Django 4.2.6 on 2024-02-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_user_name_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
